# Generated by Django 4.0.3 on 2022-04-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_creat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('citiy', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Samarqand', 'Samarqand'), ('Andijon', 'Andijon'), ('Surxondaryo', 'Surxondaryo')], default='Toshkent', max_length=11)),
                ('salary', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=13)),
                ('decription', models.TextField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35)),
                ('genders', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], default='Erkak', max_length=5)),
                ('citiy', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Samarqand', 'Samarqand'), ('Andijon', 'Andijon'), ('Surxondaryo', 'Surxondaryo')], default='Toshkent', max_length=11)),
                ('phone', models.CharField(max_length=13)),
                ('birth_date', models.DateField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('experience', models.PositiveIntegerField()),
                ('salary', models.PositiveIntegerField()),
                ('decription', models.TextField()),
            ],
        ),
    ]
